theme: jekyll-theme-minimal
title: Northwestern's Penguin Club Website
description: This website contains the learning materials for a 3 part workshop on Penguin Basics.
show_downloads: false # shows download links for the repository
logo: handoff.gif # can easily be replaced with an institutional logo by uploading a new file
